spring.application.name=Lab5

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

spring.data.mongodb.database=test

spring.data.mongodb.username=user
spring.data.mongodb.password=pass

spring.data.mongodb.authentication-database=admin
