apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: devops-project
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: {{ .Values.db.uri | quote }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/v1/users
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/users
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20