apiVersion: v1
kind: Service
metadata:
  name: devops-project-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-project
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080